version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: spotify
      MONGO_INITDB_ROOT_PASSWORD: spotify
      MONGO_DATABASE_NAME: app
    ports:
      - "27022:27017"